documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

github:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "CODEOWNERS"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/pyproject.toml"
          - "**/requirements*.txt"
          - "**/Dockerfile"
          - "**/Package.swift"
          - "**/*.csproj"
          - "**/*.gradle"
          - "**/*.gradle.kts"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "test/**"
          - "tests/**"
          - "**/*Test.*"
          - "**/*Tests.*"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "app/**"
          - "lib/**"
