name: Dependabot queue events

on:
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  queue:
    uses: ./.github/workflows/dependabot-automerge.yml
    secrets:
      app-private-key: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
