name: .NET reusable

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: 10.0.x
      test_working_directory:
        description: Directory containing the test project.
        required: true
        type: string
      application_project:
        description: Optional Windows application project path. Leave empty to skip.
        required: false
        type: string
        default: ''
      install_openssh:
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build:
    name: .NET build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install OpenSSH
        if: ${{ inputs.install_openssh }}
        run: |
          sudo apt-get update
          sudo apt-get install --yes openssh-client openssh-server
      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Restore dependencies
        working-directory: ${{ inputs.test_working_directory }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ inputs.test_working_directory }}
        run: dotnet build --no-restore
      - name: Test
        working-directory: ${{ inputs.test_working_directory }}
        run: dotnet test --no-build --verbosity normal

  application:
    name: Windows application
    if: ${{ inputs.application_project != '' }}
    runs-on: windows-2025
    env:
      APPLICATION_PROJECT: ${{ inputs.application_project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Build Windows application
        run: dotnet build "$env:APPLICATION_PROJECT" -c Release -p:Platform=x64
