name: Gradle reusable

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
      dependency_submission:
        required: false
        type: boolean
        default: true
      dependency_projects:
        required: false
        type: string
        default: ':app'
      dependency_configurations:
        required: false
        type: string
        default: '.*[Rr]untimeClasspath'

jobs:
  build:
    name: Gradle build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: ${{ inputs.java_version }}
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      - name: Build with Gradle Wrapper
        working-directory: ${{ inputs.working_directory }}
        run: ./gradlew build

  dependency-submission:
    name: Gradle dependency submission
    if: ${{ github.event_name == 'push' && inputs.dependency_submission }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: ${{ inputs.java_version }}
          distribution: temurin
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          build-root-directory: ${{ inputs.working_directory }}
          dependency-graph-include-projects: ${{ inputs.dependency_projects }}
          dependency-graph-include-configurations: ${{ inputs.dependency_configurations }}
